""" Production Configurations """

SECRET_KEY = ''
SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_TRACK_MODIFICATIONS = False
PREFERRED_URL_SCHEME = "https"

SESSION_TYPE = 'filesystem'

APP_LOG_FILE = ''
APP_LOG_LEVEL = 'INFO'
